### ISSUE TITLE
README какая инструкция? Как привязать своё вк-приложение к локальному тунелю?

### ISSUE THREAD

**Issue by ibyteyou** [VKCOM/vk-tunnel-client#19]
<img width="873" alt="Снимок экрана 2022-07-20 в 01 22 52" src="https://user-images.githubusercontent.com/16253399/179858473-f83b349a-a9a8-4c25-a5fb-7dc392d9345e.png">

**Comment by hit2hat** [comment]
Привет!

Чтобы "привязать" мини-приложение вконтакте к локальному туннелю, надо указать нужный `app_id` в `vk-tunnel-config.json`.

Чтобы создать мини-приложение [если по какой-то причине этого не было сделано раньше] воспользуйтесь [инструкцией](https://dev.vk.com/mini-apps/getting-started).

**Comment by pasha-nikitin-2003** [comment]
Вы также можете обратиться к [документации туннеля](https://dev.vk.com/libraries/tunnel).
Или создать мини апп через [create-vk-mini-app](https://github.com/VKCOM/create-vk-mini-app) с уже настроенным туннелем.
