### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by iskizreal** [VKCOM/vk-tunnel-client#22]
При запуске:
`vk-tunnel --insecure=0 --http-protocol=https --ws-protocol=wss --host='192.168.1.31' --port=3000`

Получаю такую ошибку:

```
["2023-01-31T15:58:30.980Z"] ERROR: Connect Error: Error: Server responded with a non-101 status: 200 OK
Response Headers Follow:
server: kittenx
date: Tue, 31 Jan 2023 15:58:30 GMT
content-length: 0
connection: keep-alive
keep-alive: timeout=300
```
Пробовал много разных вариантов запуска, например:
```
vk-tunnel
vk-tunnel --port 3000
```
Проблема с коннектом к ВК. Есть идеи? Спасибо

**Comment by BigBush3** [comment]
тоже самое

**Comment by alexilins** [comment]
аналогично
`["2023-01-31T17:56:06.482Z"] ERROR: Connect Error: Error: Server responded with a non-101 status: 200 OK
Response Headers Follow:
server: kittenx
date: Tue, 31 Jan 2023 17:56:06 GMT
content-length: 0
connection: keep-alive
keep-alive: timeout=300`

**Comment by PonomareVlad** [comment]
Вот и первый звоночек... 🙂

**Comment by AlekseyChepurko** [comment]
присоединяюсь к негодующим :)

**Comment by Space1nvader** [comment]
Вместе с падением онлифанса упал и вк-тунель :(

**Comment by Di-Pol** [comment]
> Вот и первый звоночек... 
Да, их симптомы не радуют: "Дело в том, что выполнять хранимые процедуры через веб-интерфейс возможно только в приложениях с типом Standalone. Вам необходимо вызывать эту функцию в коде, либо создать другое приложение."
Они уволили всех, кто знал, как с авторизацией работать?

**Comment by PonomareVlad** [comment]
Уже пора поднимать свой аналог ?

**Comment by ilyapishchulin** [comment]
Спасибо за issue, мы исправили проблему сегодня ночью, теперь всё должно быть хорошо
