### ISSUE TITLE
Решение проблемы с установкой пакета на Windows

### ISSUE THREAD

**Issue by Stiv455** [VKCOM/vk-tunnel-client#24]
### Поставьте Visual Studio - проблемы как рукой снимет. node-gyp нужен компилятор, чтобы пересобрать себя из исходников.
Он же буржуйским языком говорит ошибку:
Не установлена переменная **msvs_version** (в которой должна храниться версия Visual Studio).
Тогда пытается прочитать переменную **VCINSTALLDIR** (в которой должен быть путь к папке установленной Visual Studio) и там неудача.
Говорит, что ни Visual Studio 2017+ ни Visual Studio 2015 не установлено. Более старые - не подойдут.

1. Скачайте установщик [Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)
2. Запустите установщик.
3. Установите флажок Разработка классических приложений на C++.
4. Нажмите кнопку Установить. Дождитесь окончания установки.
5. Откройте командную строку и выполните команду: 
```shell
npm config set msvs_version 2017
``` 
Готово..

### Зачем устанавливать C++?
Модули, написанные на С++, используются в библиотеках ВКонтакте. Для компиляции кода на C++ используется node-gyp, который устанавливается вместе с Node.js и может вызывать ошибки, если C++ не установлен.

**Comment by NoMoreNap** [comment]
`msvs_version` is not a valid npm option

**Comment by s0loparty** [comment]
+ нужен фикс

**Comment by pasha-nikitin-2003** [comment]
Добрый день! Исправили проблемы с установкой в версии 0.2.0.
