### ISSUE TITLE
Vite React + Vk Tunnel

### ISSUE THREAD

**Issue by b5414** [VKCOM/vk-tunnel-client#30]
Не понимаю как настроить Vite и Туннель чтобы они работали нормально и сообща, несколько вариаций настроек я приложил ниже, а именно: два скрипта запуска и вайт конфиг.. 

Максимум чего я смог добиться - это запуска приложения в wormhole (по ссылке, что выдает туннель), т.е. он  но в вк _мне кажется что веб сокет не отдает какую-то информацию_ и всегда висит лоадер, но если через елементы его удалить, то я увижу своё приложение в самом вк, т.е. все то что нужно мне (всем)

Может быть это баг самого вк, не уверен, но туннелирование прокает и лоадер пропадает если я запускаюсь через вебпак (с условием что меняю у скрипта хост с 0000 на localhost)

пс уточню, что лоадер выше - от вк (вроде) внутри iframe, т.е. не от моего проекта

- [полезно 1](https://github.com/nikitakoschelenko/vkma-template/tree/main#использование-с-vk-tunnelngroketc) 
- [полезно 2](https://github.com/ExercisesMiniApp/Frontend/tree/master)

# package.json

```json
{
	"start": "vite",
	"startD": "vite --port 3002",
	"startA": "vite --port 3002 --https",

	"tunnel": "vk-tunnel --port=3002",
	"tunnelZ": "vk-tunnel --insecure=1 --http-protocol=https --ws-protocol=wss --host=0.0.0.0 --port=3002",
	"tunnelV": "vk-tunnel --insecure=1 --http-protocol=https --ws-protocol=wss --host=localhost --port=3002",
}
```

+ `+ endpoints=[web]`
+ `+ app_id=5175414`

# vite.config.js

```js
import basicSsl from '@vitejs/plugin-basic-ssl';

//

export default defineConfig({
	plugins: [react(), basicSsl()],
});

// or

export default defineConfig({
	server: {
		hmr: {
			clientPort: 443,
		},
	},
	plugins: [react(), basicSsl()],
});

// or

export default defineConfig({
	plugins: [react()],
	build: {
		target: 'es2015',
		assetsInlineLimit: 0,
		minify: 'terser',
		terserOptions: {
			compress: {
				drop_console: true,
				dead_code: true,
			},
			toplevel: false,
			keep_classnames: false,
			keep_fnames: false,
			safari10: false,
		},
	},
});
```

**Comment by pasha-nikitin-2003** [comment]
Запустил [первый пример](https://github.com/nikitakoschelenko/vkma-template/tree/main#использование-с-vk-tunnelngroketc) на последней версии туннеля - все корректно работает.

```
yarn global add @vkontakte/vk-tunnel
vk-tunnel --insecure=0 --http-protocol=https --ws-protocol=wss --host=localhost --port=5173 --timeout=5000
```

Пару моментов:

- Можно поддержать hot-reload в vk-tunnel, если добавить это в настройки vite-config:
```
    hmr: {
      protocol: 'wss', 
      host: 'localhost' 
    }
```
- Лучше использовать [наш роутер](https://github.com/VKCOM/vk-mini-apps-router) - @itznevikat/router менее настраиваемый и больше не поддерживается. Подробнее о возможностях можно почитать [тут](https://dev.vk.com/ru/libraries/router).
- Лучше использовать оригинальный [vk-bridge](https://github.com/VKCOM/vk-bridge), а не его зеркало. Если возникнет необходимость добавить в наши библиотеки новую функциональность - мы открыты к предложениям.
