### ISSUE TITLE
Не устанавливается @vkontakte/vk-tunnel на виндовс

### ISSUE THREAD

**Issue by Banini121** [VKCOM/vk-tunnel-client#34]
Не понимаю в чем проблема... Уже все перепробовал. Устанавливал разные версий питона, ноде жс. с++ заново накатывал. Итоге ничего не помогает 

C:\Users\Хацкер>npm install @vkontakte/vk-tunnel -g
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Хацкер\\AppData\\Roaming\\npm\\node_modules\\@vkontakte\\vk-tunnel',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Хацкер\AppData\Roaming\npm\node_modules\@vkontakte\vk-tunnel\node_modules\resolve\test\resolver\without_basedir'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Хацкер\\AppData\\Roaming\\npm\\node_modules\\@vkontakte\\vk-tunnel\\node_modules\\resolve\\test\\resolver\\without_basedir'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Хацкер\AppData\Roaming\npm\node_modules\@vkontakte\vk-tunnel\node_modules\websocket
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - executable path is "C:\Users\������\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\������\AppData\Local\Programs\Python\Python312\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is "C:\Users\������\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\������\AppData\Local\Programs\Python\Python312\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python311-32\python.exe" could not be runnpm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python310\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python310\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python310-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python310-32\python.exe" could not be runnpm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python310-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python310-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python310-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python310-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python39-32\python.exenpm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\Хацкер\AppData\Local\Programs\Python\Python38-32\python.exenpm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\Хацкер\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:306:11)
npm ERR! gyp ERR! stack at PythonFinder.findPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:164:17)
npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! gyp ERR! stack at async configure (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:23:18)
npm ERR! gyp ERR! stack at async run (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Хацкер\AppData\Roaming\npm\node_modules\@vkontakte\vk-tunnel\node_modules\websocket
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

**Comment by nshvyryaev** [comment]
Здравствуйте!
У пакета есть проблемы с установкой на Windows - зависимости от специфичных библиотек C++ и версии питона.

Попробуйте, пожалуйста, запустить через докер, как описано тут https://github.com/VKCOM/vk-tunnel-client/issues/33

**Comment by Banini121** [comment]
А можно как-то без него? Просто даже этот докер не устанавливается на пк

**Comment by nshvyryaev** [comment]
Можно запустить и без докера. К сожалению, у нас сейчас нет готовой инструкции для запуска на Windows непосредственно - проблемы бывают разные у разных пользователей с разными установками. В некоторых случаях помогает установка VisualStudio (не Code) - в нем есть нужные библиотеки С++.

В целом, мы хотим исследовать возможность изменения зависимостей библиотеки так, чтобы она стабильно работала и на Windows. Эта работа в планах на февраль-март.

**Comment by pasha-nikitin-2003** [comment]
Добрый день! Исправили проблемы с установкой в версии 0.2.0.
