### ISSUE TITLE
Библиотека не устанавливается

### ISSUE THREAD

**Issue by DayensCode** [VKCOM/vk-tunnel-client#40]
### Описание

Windows 10 Pro  x64-based PC
Python version 3.12.2
Visual Studio 2022

node v20.11.1
npm 10.4.0

### Версия vk-tunnel-client

0.1.4

### Платформа

Windows

### Шаги воспроизведения

npm install @vkontakte/vk-tunnel --include=dev

### Ожидаемое поведение

-------------------------------------------------------------------------------------------------------------------------------------------------

### Скриншоты

Доступна, но не ставится

![2024-03-01_00-47-35](https://github.com/VKCOM/vk-tunnel-client/assets/113854236/d8066895-d6e6-4120-b3a7-fa0ba555e1fb)

### Код, который вызвал ошибку

npm ERR! code 1
npm ERR! path C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! bufferutil.cc
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23): error C2039: "AccessorSignature": �� ���� 童��� "v8". [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8.h(71,11):
npm ERR!    �. ������� "v8"
npm ERR!   
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23): error C2065: AccessorSignature: ��������� �����䨪��� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,13): error C2923: v8::Local: "AccessorSignature" �� ���� �����⨬� ��㬥�⮬ ⨯� 蠡��� ��� ��ࠬ��� "T" [C:\Users\Alexandr\dev\vk-to
do\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23):  
npm ERR!    �. ������� "AccessorSignature"
npm ERR!   
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,42): error C2955: "v8::Local": ��� �ᯮ�짮����� ����� 蠡��� �ॡ���� ᯨ᮪ ��㬥�⮢ 蠡��� [C:\Users\Alexandr\dev\vk-todo\node_modules\
@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,14): error C2955: "v8::Local": ��� �ᯮ�짮����� ����� 蠡��� �ॡ���� ᯨ᮪ ��㬥�⮢ 蠡��� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontak
te\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2641: �� 㤠���� �뢥�� ��㬥��� 蠡���� ��� "v8::Local". [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(T *)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(331,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(v8::Local<S>)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(195,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2783: "v8::Local<T> v8::Local(void)": �� 㤠���� �뢥�� ��㬥�� 蠡��� ��� "T" [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(192,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(v8::Local<T>)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6): error C2665: "v8::ObjectTemplate::SetAccessor": �� ���� ��ॣ�㦥���� �㭪�� �� ����� �८�ࠧ����� �� ⨯� ��㬥�⮢ [C:\Users\Alexandr\dev\v
k-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\bufferutil.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/bufferutil.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-template.h(816,8):
npm ERR!   ����� ���� "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)"
npm ERR!        C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):      
npm ERR!        "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)": ���������� �८�ࠧ����� ��㬥�� 7 �� "Nan::imp::Sig" � "v8::SideEffectType"
npm ERR!                C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2542,7):
npm ERR!                ��� �믮������ ������� �८�ࠧ������ ��� ����㯭��� ������ �८�ࠧ������, ��।�������� ���짮��⥫��, ���
 �맮� ������ ����������
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-template.h(809,8):
npm ERR!   ���       "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)"
npm ERR!        C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):      
npm ERR!        "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)": ���������� �८�ࠧ����� ��㬥�� 2 �� "Nan::imp::NativeGetter" � "v8::AccessorGetterCallback"
npm ERR!                C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2537,7):
npm ERR!                ��� �८�ࠧ������ �ॡ���� reinterpret_cast, �ਢ������ � �⨫� � ��� �ਢ������ � �⨫� �㭪樨 � ��㣫�� ᪮�
���
npm ERR!   C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):
npm ERR!   �� ����⪥ ᮯ��⠢��� ᯨ᮪ ��㬥�⮢ "(v8::Local<v8::String>, Nan::imp::NativeGetter, Nan::imp::NativeSetter, v8::Lo
cal<v8::Object>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)"
npm ERR!   
npm ERR!   validation.cc
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23): error C2039: "AccessorSignature": �� ���� 童��� "v8". [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8.h(71,11):
npm ERR!    �. ������� "v8"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23): error C2065: AccessorSignature: ��������� �����䨪��� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,13): error C2923: v8::Local: "AccessorSignature" �� ���� �����⨬� ��㬥�⮬ ⨯� 蠡��� ��� ��ࠬ��� "T" [C:\Users\Alexandr\dev\vk-to
do\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,23):  
npm ERR!    �. ������� "AccessorSignature"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan_callbacks.h(55,42): error C2955: "v8::Local": ��� �ᯮ�짮����� ����� 蠡��� �ॡ���� ᯨ᮪ ��㬥�⮢ 蠡��� [C:\Users\Alexandr\dev\vk-todo\node_modules\
@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,14): error C2955: "v8::Local": ��� �ᯮ�짮����� ����� 蠡��� �ॡ���� ᯨ᮪ ��㬥�⮢ 蠡��� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontak
te\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2641: �� 㤠���� �뢥�� ��㬥��� 蠡���� ��� "v8::Local". [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(T *)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(331,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(v8::Local<S>)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(195,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2783: "v8::Local<T> v8::Local(void)": �� 㤠���� �뢥�� ��㬥�� 蠡��� ��� "T" [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(192,3):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2509,34): error C2780: "v8::Local<T> v8::Local(v8::Local<T>)": ��������� ��㬥��� 1 - 0 �।��⠢���� [C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-local-handle.h(190,7):
npm ERR!    �. ������� "v8::Local"
npm ERR!
npm ERR! C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6): error C2665: "v8::ObjectTemplate::SetAccessor": �� ���� ��ॣ�㦥���� �㭪�� �� ����� �८�ࠧ����� �� ⨯� ��㬥�⮢ [C:\Users\Alexandr\dev\v
k-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket\build\validation.vcxproj]
npm ERR!   (��������� ��室���� 䠩�� "../src/validation.cc")
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-template.h(816,8):
npm ERR!   ����� ���� "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)"
npm ERR!        C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):      
npm ERR!        "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)": ���������� �८�ࠧ����� ��㬥�� 7 �� "Nan::imp::Sig" � "v8::SideEffectType"
npm ERR!                C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2542,7):
npm ERR!                ��� �믮������ ������� �८�ࠧ������ ��� ����㯭��� ������ �८�ࠧ������, ��।�������� ���짮��⥫��, ���
 �맮� ������ ����������
npm ERR!   C:\Users\Alexandr\AppData\Local\node-gyp\Cache\20.11.1\include\node\v8-template.h(809,8):
npm ERR!   ���       "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)"
npm ERR!        C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):      
npm ERR!        "void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)": ���������� �८�ࠧ����� ��㬥�� 2 �� "Nan::imp::NativeGetter" � "v8::AccessorGetterCallback"
npm ERR!                C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2537,7):
npm ERR!                ��� �८�ࠧ������ �ॡ���� reinterpret_cast, �ਢ������ � �⨫� � ��� �ਢ������ � �⨫� �㭪樨 � ��㣫�� ᪮�
���
npm ERR!   C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\nan\nan.h(2535,6):
npm ERR!   �� ����⪥ ᮯ��⠢��� ᯨ᮪ ��㬥�⮢ "(v8::Local<v8::String>, Nan::imp::NativeGetter, Nan::imp::NativeSetter, v8::Lo
cal<v8::Object>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)"
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.9.34622.214) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\\Users\\Alexandr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Alexandr\\dev\\vk-todo\\node_modules\\@vkontakte\\vk-tunnel\\node_modules\\websocket\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Alexandr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Alexandr\\AppData\\Local\\node-gyp\\Cache\\20.11.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\Alexandr\\AppData\\Local\\node-gyp\\Cache\\20.11.1',        
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\Alexandr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\Alexandr\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.11.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\\Users\\Alexandr\\dev\\vk-todo\\node_modules\\@vkontakte\\vk-tunnel\\node_modules\\websocket',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\\Users\\Alexandr\\dev\\vk-todo\\node_modules\\@vkontakte\\vk-tunnel\\node_modules\\websocket\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'build\\binding.sln',
npm ERR! gyp info spawn args '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args '/nologo',
npm ERR! gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Alexandr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alexandr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Alexandr\dev\vk-todo\node_modules\@vkontakte\vk-tunnel\node_modules\websocket
npm ERR! gyp ERR! node -v v20.11.1
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\Alexandr\AppData\Local\npm-cache\_logs\2024-02-29T21_59_42_435Z-debug-0.log

**Comment by pasha-nikitin-2003** [comment]
Добрый день, баг уже в работе, в течение пары недель мы выпустим обновление с исправлением, пока можете воспользоваться советами в #33, где обсуждается эта проблема.

**Comment by pasha-nikitin-2003** [comment]
Добрый день! Исправили проблемы с установкой в версии 0.2.0.
