### ISSUE TITLE
[Bug]: Error: socket hang up

### ISSUE THREAD

**Issue by ivan-mel** [VKCOM/vk-tunnel-client#49]
### Описание

Начиная с 0.1.7 при открытии полученной ссылки вылезает ошибка в консоли `Error: socket hang up`.
Раньше всё работало.

### Версия vk-tunnel-client

0.1.7

### Платформа

Windows

### Шаги воспроизведения

1. Запустить проект по адресу https://localhost:5173/ через `vite 5` и плагин `@vitejs/plugin-basic-ssl`

2. Заполнить `vk-tunnel-config.json`  и запустить команду `vk-tunnel --host=localhost --timeout=10000`
```
{
  "app_id": "51658481",
  "endpoints": [
    "mobile",
    "mvk",
    "web"
  ],
  "port": "5173",
  "http-protocol": "https",
  "insecure": "1" // 0 тоже не работает
}
```
3. открыть полученную ссылку в любом месте (из приложения или напрямую - не важно, ошибка одна)

### Ожидаемое поведение

Ошибки не должно быть и веб приложение должно загружаться.

### Скриншоты

![image](https://github.com/VKCOM/vk-tunnel-client/assets/157804366/0e3fc87f-4c65-48b4-8e58-7af4fe3e1553)

**Comment by ivan-mel** [comment]
П.с. по http всё работает, но хотелось бы и по https.

**Comment by quick6response** [comment]
Поддерживаю, ранее такая поддержка была!

**Comment by pasha-nikitin-2003** [comment]
Добрый вечер! Исправили проблемы с подключением по https соединению в версии 0.2.0.
Также в 0.2.0 было изменено описание поля `insecure` в документации:
  - Значение `0` теперь указывает на пропуск проверки сертификата.
  - Значение `1` теперь указывает на выполнение проверки сертификата.
  - По умолчанию указан 0.
